name: "Curriculum Vitae - Midhul Varma"
description: ""

url: "http://midhul.github.io/cv/"

collections:
  test:
    output: true
    permalink: /test/:path/
  info:
    output: true
  projects:
    output: true

markdown: rdiscount
permalink: pretty