name: "Curriculum Vitae - Midhul Varma"
description: ""

url: "http://midhul.github.io/cv/"

collections:
  info:
    output: true
  projects:
    output: true
    permalink: /projects/:path/

markdown: rdiscount
permalink: pretty